---

- name: Check that {{ vsts_agent_check }} exists
  stat:
    path: "{{ vsts_agent_check }}"
  register: vsts_agent_check_result

- name: create vsts agent directory
  file:
    owner: "{{ vsts_user }}"
    group: "{{ vsts_group }}"
    mode: '0750'
    state: directory
    path: "{{ vsts_agent_path }}"
  when: not vsts_agent_check_result.stat.exists

- name: Get vsts agent
  unarchive:
    owner: "{{ vsts_user }}"
    group: "{{ vsts_group }}"
    remote_src: yes
    src: "{{ vsts_agent_url }}"
    dest: "{{ vsts_agent_path }}"
  when: not vsts_agent_check_result.stat.exists

- name: Configure vsts agent
  command: |
    ./config.sh \
    --deploymentGroup \
    --deploymentGroupName "{{ vsts_deployment_group }}" \
    --acceptteeeula \
    --agent {{ ansible_hostname }} \
    --url {{ vsts_project_url }} \
    --work {{ vsts_project_work_group }} \
    --projectname {{ vsts_project_name }} \
    --addDeploymentGroupTags \
    --deploymentGroupTags "{{ vsts_group_tags }}" \
    --auth PAT --token {{ vsts_token }} \
    --runasservice
  become: yes
  become_user: "{{ vsts_user }}"
  args:
    chdir: "{{ vsts_agent_path }}"
  when: not vsts_agent_check_result.stat.exists

- name: Install vsts agent
  command: ./svc.sh install
  become: yes
  become_user: "{{ vsts_user_admin }}"
  args:
    chdir: "{{ vsts_agent_path }}"
  when: not vsts_agent_check_result.stat.exists

- name: Initiate vsts agent
  command: ./svc.sh start
  become: yes
  become_user: "{{ vsts_user_admin }}"
  args:
    chdir: "{{ vsts_agent_path }}"
  when: not vsts_agent_check_result.stat.exists

- name: create vsts agent check file
  file:
    owner: "{{ vsts_user }}"
    group: "{{ vsts_group }}"
    mode: '0600'
    state: touch
    path: "{{ vsts_agent_check }}"
  when: not vsts_agent_check_result.stat.exists
